### ISSUE TITLE
MongoFrames doesn't delete document

### ISSUE THREAD

**Issue by njordr** [GetmeUK/MongoFrames#13]
Hi.

A strange issue: the Frame class doesn't delete the document from the db. Insert and update works fine.

```
            str_id = '{}_{}_{}_{}_{}'.format(
                data_before.get('CodImpianto'),
                data_before.get('Armadio'),
                data_before.get('DateVar'),
                data_before.get('ShelfEvent'),
                data_before.get('Counter'),
            )
            log_id = sha224(str_id.encode()).hexdigest()
            previous_record = SDClosetLogs().by_id(log_id)

            if previous_record is not None:
                logger.debug('Deleting document {}.'.format(previous_record._id))
                try:
                    # previous_record.delete()
                    SDClosetLogs.delete(SDClosetLogs().by_id(log_id))
                except Exception as e:
                    logger.error('Cannot delete document {}. Error: {}'.format(previous_record._id, e))
                    return False
```

This is the log:
2016-12-11 16:30:36 DEBUG 3700 spy_replicator.etl_modules.etl_spydoc etl_spydoc.py:219 => Deleting document c4e599fb7467db9f868746631b7daea81a32fc63a2be05871b5710d8. (no exception logged)
I tried using both the previous_record instance and the general Frame class.

This is the documents in collections pre and after the delete operation:
![image](https://cloud.githubusercontent.com/assets/4282925/21081488/66b505fa-bfc8-11e6-82de-f74e94adf0f0.png)

This is the Frame class

```
class SDClosetLogs(Frame):
    _db = 'spy'
    _collection = 'logs'
    _fields = {
        '_id',
        'date',
        'type',
        'subtype',
        'installation',
        'closet',
        'shelf_event',
        'tag_id',
        'tag_user',
        'description',
        'counter'
    }
```

**Comment by anthonyjb** [comment]
Hi @njordr - we use the delete function quite a bit and clearly it passes the tests currently so my guess would be that this is specific to your scenario, like you highlight I'd typically expect this to be done like so:

```python
SDClosetLogs().by_id(log_id).delete()
```

If this isn't working then it sounds like the something specific to the `SDClosetLogs` class set up is causing the issue, could you post the code for that class so I can review please?

**Comment by njordr** [comment]
This is my SDClosetLogs class

```
class SDClosetLogs(Frame):
    _db = 'spy'
    _collection = 'logs'
    _fields = {
        '_id',
        'date',
        'type',
        'subtype',
        'installation',
        'closet',
        'shelf_event',
        'tag_id',
        'tag_user',
        'description',
        'counter'
    }
```

**Comment by anthonyjb** [comment]
@njordr - maybe it's an issue setting the `_collection` or `_db`, everything looks fine with it. I'll set it up on my local machine and attempt to add a record, find it by ID then delete it. I'll let you know how I get on, btw are you setting the ID (`_id`) manually or allowing mongo to provide one?

**Comment by njordr** [comment]
I set the _id field manually

**Comment by anthonyjb** [comment]
OK I'll make sure I do also, are you storing an ObjectID as the ID or are just a hash string?

**Comment by njordr** [comment]
hash string

**Comment by anthonyjb** [comment]
@njordr - So the following code sample works correctly for me, can you confirm it works for you or if it raises an error to help track the source of the issue?

```Python
from pymongo import MongoClient
from mongoframes import Frame


# Connect to database via MongoFrames
Frame._client = MongoClient(
    'mongodb://localhost:27017/njordr_test'
    )


# Define the docyment
class SDClosetLogs(Frame):
    _db = 'spy'
    _collection = 'logs'
    _fields = {
        '_id',
        'date',
        'type',
        'subtype',
        'installation',
        'closet',
        'shelf_event',
        'tag_id',
        'tag_user',
        'description',
        'counter'
    }


# Insert a document
document = SDClosetLogs(
    _id='c4e599fb7467db9f868746631b7daea81a32fc63a2be05871b5710d8',
    date='2016-12-11',
    type='foo',
    subtype='bar',
    installation=True,
    closet=False,
    shelf_event=True,
    tag_id='746631b7daea81a32fc63a2be05871b5710d8c4e599fb7467db9f868',
    tag_user='Ad8c4e599fb7467db9f746631b7daea81a32fc63a2be05871b5710d8',
    description='MongoFrames is a fast unobtrusive MongoDB ODM for Python \
        designed to fit into a workflow not dictate one.',
    counter=1
    )
document.insert()

# Check a document was inserted
print(SDClosetLogs.count())


# Find and delete the same document
document_ref = SDClosetLogs.by_id(document._id)
try:
    document_ref.delete()
except Exception as e:
    print(e)

# Check the document was deleted
print(SDClosetLogs.count()) 
```

**Comment by anthonyjb** [comment]
The result should of course print out:

```
1
0
```

**Comment by njordr** [comment]
it works, I need to recheck carefully my code.

many thanks for your time

**Comment by anthonyjb** [comment]
No problem, let me know how you get on and if I can help further :)

**Comment by njordr** [comment]
Stupid bug: I used the same code to update or delete a record: it didn't exit in case of delete, so it re-create the document (the right way in case of update task)
