### ISSUE TITLE
Performance improvement by using ctypes

### ISSUE THREAD

**Issue by TheGent** [GetmeUK/MongoFrames#15]
Hi,
I had the idea to integrate ctypes/Structure. I imagined that somehow:
1. Get the meta data of the collection (field -> type)
2. Build a object template by mongodb -> ctypes mapping definition
3. Use the ctypes object template to construct the objects

I've already started my own experiment and I have to say that the performance gain is enormous:
```
class Attribute(Frame):
    __metaclass__ = ctypes.Structure
    _collection = 'system_attribute'
    _fields = {
        'key',
        'label',
        'description',
        'metadata',
        'field_class',
        'multivalue',
        'tags',
    }

    _fields_ = [
        ('key', ctypes.c_char),
        ('label', ctypes.c_char),
        ('description', ctypes.c_char),
        ('field_class', ctypes.c_char),
        ('multivalue', ctypes.c_bool),
        ('tags', ctypes.Union),
    ]
```
Let me know what you think

**Comment by anthonyjb** [comment]
Hi @TheGent sorry I haven't gotten around to replying yet, I am still intending to review your example, I'm very interested in the performance improvements you mentioned. Is there a reason you've closed the issue?
