### ISSUE TITLE
document with _id

### ISSUE THREAD

**Issue by njordr** [GetmeUK/MongoFrames#4]
Hi

How to insert a document with an _id field?

Thanks

**Comment by anthonyjb** [comment]
Hi @njordr, 

That's a really good point, I've put an assert into prevent people accidentally calling `insert` against a document when they mean't to call `update` but the reality is that you may want to insert a document with an `_id` and this wasn't a sensible decision.

I'll remove the assert today and push a new version to PyPi.

**Comment by njordr** [comment]
Thanks :)

**Comment by njordr** [comment]
There is a use case I cannot address with MongoFrames.

I can make an upsert if I got a document _id, but usually I use the upsert function of mongodb without know if the document already exists.

In MongoFrame if I don't know the id and I call the upsert withouth an _id field.

I tried:
class Outage(Frame):
    _collection = 'outages'
    _fields = {
        '_id',
        'start_time',
        'end_time',
        'monitor_id',
        'id',
        'source'
    }

doc = Outage(
        _id='kfdwnjefwifrlglweqrg',
        start_time=datetime.now(),
        end_time=datetime.now(),
        monitor_id='8746857636238498',
        id='kfdwnjefwifrlglweqrg',
        source='site24'

    )
doc.upsert()

It doen't return an error but the document is not inserted.

please let me know if I misundestrood your library

**Comment by anthonyjb** [comment]
This is down to the same incorrect  assumption I made regarding providing an Id on insert, I'll look at addressing it now. (I've resolved the `_id` issue for insert so will push that once I fix upsert as well).

**Comment by anthonyjb** [comment]
Hi @njordr - so I've pushed a new release ([1.0.2](https://github.com/GetmeUK/MongoFrames/releases/tag/1.0.2)) that solves these two issues,

- You can now manually specify an `_id` value when inserting a document.
- The `upsert` method now checks to see if there's a document associated with the `_id` before calling `insert`/`update`.

> NOTE: This method is not the same as specifying the `upsert` flag when calling MongoDB. When called for a document with an `_id` value, this method will call the database to see if a record with that Id exists, if not it will call `insert`, if so it will call `update`. This operation is therefore not atomic and much slower than the equivalent MongoDB operation (due to the extra call).

As a possible alternative, if you want to perform an upsert using the underlying pymongo library you could do something a long the lines of:

```python
from mongoframes.queries import to_refs

result = my_doc.get_collection().update(
    {'_id': my_Doc._id}, 
    to_refs(my_doc._document), 
    upsert=True
    )
```
