### ISSUE TITLE
issue with Frame.by_id

### ISSUE THREAD

**Issue by njordr** [GetmeUK/MongoFrames#6]
Hi.

I've this document:
{
    "_id" : "report_xyz",
    "name" : "XYZ.COM",
    "site24" : {
        "monitors" : [ 
            NumberLong(27498547952905495), 
            NumberLong(18975984759794899), 
            NumberLong(19875894954998994), 
            NumberLong(14987598437950899), 
            NumberLong(17498574975919809)
        ]
    }
}

If I try to get it with by_id this is the error:
bson.errors.InvalidId: 'report_xyz' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

Giovanni

**Comment by anthonyjb** [comment]
Hi @njordr - yep this is a bug :) I incorrectly assumed that `_id`s will always be `ObjectId`s and automatically convert whatever value is passed to one, which I don't need to do - I'll fix today and push a new release to pip.

In the short-term (e.g before I fix this) you can use the following as a work around:

```python
my_frame = MyFrame.one(Q._id == 'report_xyz')
```

**Comment by njordr** [comment]
Already done, thanks for the advice

**Comment by anthonyjb** [comment]
OK @njordr that should be resolved and the new release (1.0.3) is now up on PyPi :) 

Thanks for your help so far it's been very useful to have someone using the library and providing feedback.
