### ISSUE TITLE
frameless with check for defined fields

### ISSUE THREAD

**Issue by njordr** [GetmeUK/MongoFrames#7]
Hi.

I've created a frameless class as stated here: http://mongoframes.com/snippets/frameless and it works like a charm :)

What about to introduce a check for the defined fields?

Here is an example of my frameless class:

    class InfluxMetric(Frameless):
        _collection = 'influxdb_metrics'
        _fields = {
            '_id',
            'test'
        }

Is it possible to force the new class to fill-in at least the two defined fields (_id and test)?

Thanks,
Giovanni

**Comment by anthonyjb** [comment]
Hi @njordr - you could consider the data validation approach in this snippet here: http://mongoframes.com/snippets/data-validation. If you only want to check that fields have a value then the `save` method presented could be significantly reduced (e.g no need for form validation).

**Comment by njordr** [comment]
I can use validation also on frameless? If so, sorry for the question :(

**Comment by anthonyjb** [comment]
Sorry no you would need to mixin the validation stuff with Frameless e.g you might do something along the lines of:

```Python
class ValidatedFrameless(Frameless)

    # The form attribute should be assigned a WTForm class
    _form = None

    def save(self, *fields):
        """Validate the document before inserting/updating it"""

        # If no form is defined then validation is skipped
        if not self._form:
            return self.upsert(*fields)

        # Build the form data
        if not fields:
            fields = self.fields

        data = {f: self[f] for f in fields if f in self}

        # Build the form to validate our data with
        form = self._form(FormData(data))

        # Reduce the form fields to match the data being saved
        for field in form:
            if field.name not in data:
                delattr(form, field.name)

        # Validate the document
        if not form.validate():
            raise InvalidDocument(form.errors)

        # Document is valid, save the changes :)
        self.upsert(*fields)​​​​​​​​​​​
```

**Comment by anthonyjb** [comment]
Antother very simple approach would be to use event hooks to do this, for example:

```Python
class MyFramelessClass(Frameless):

    _required_fields = {'_id', 'other_field', ...}

    @classmethod
    def _on_insert(cls, sender, frames):
        for frame in frames:
            for field in cls._required_fields:
                assert getattr(frame, field), 'No value defined for: ' + field

MyFramelessClass.listen('insert', MyFramelessClass._on_insert)
```

> **Disclaimer:** I haven't tested this I'm just coding out loud.

**Comment by njordr** [comment]
Great, thanks!
