### ISSUE TITLE
regex support

### ISSUE THREAD

**Issue by njordr** [GetmeUK/MongoFrames#9]
Hi, here I'm back again :)

How to use regex with MongoFrame?

**Comment by anthonyjb** [comment]
Hi @njordr,

You can use it in the same way you would with PyMongo, for example to find all users with email addresses ending in `.hotmail.com` we could do:

```
User.many({'email': re.compile('\.gmail\.com$', re.I)})
```

or using MongoFrames `Q`:

```
User.many(Q.email == re.compile('\.gmail\.com$', re.I))
```

**Comment by njordr** [comment]
Great

I was trying to use it adding "$regex"

As usual, many thanks

**Comment by anthonyjb** [comment]
np :D
